#!/usr/bin/env bash
# Fail if the app family's version numbers have drifted apart.
#
# project.yml is the source of truth. Every target declares its version there
# and `xcodegen generate` writes the matching Resources/*-Info.plist, so those
# plists are build output: they are gitignored, and editing them by hand
# accomplishes nothing.
#
# Resources/Info.plist is the one exception. It cannot move into project.yml
# because three things read it off disk before xcodegen ever runs:
# scripts/build-app.sh (the SwiftPM fallback path), the Homebrew formula's
# install block, and the release workflow's tag check. So it stays hand-
# maintained, and this script is what keeps it honest — along with the two
# Homebrew files, which pin the marketing version but have no build number.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

# Hand-maintained; must match project.yml on both keys.
SOURCE_PLISTS=(
  Resources/Info.plist
)

# Hand-maintained; pin the marketing version only.
RUBY_FILES=(
  Formula/standup-reminder.rb
  Casks/standup-reminder.rb
)

# Written by xcodegen; must stay untracked or `xcodegen generate` dirties the
# tree for everyone who regenerates the project.
GENERATED_PLISTS=(
  Resources/Widget-Info.plist
  Resources/iOS-Info.plist
  Resources/Watch-Info.plist
  Resources/iOSWidget-Info.plist
  Resources/WatchWidget-Info.plist
)

status=0
fail() { echo "error: $*" >&2; status=1; }

# Collect the version each project.yml target declares. All of them must agree;
# `sort -u` reduces them to one value, so anything left over is a disagreement.
collect_yaml() {
  sed -n "s/^ *$1: *\"\{0,1\}\([^\"]*\)\"\{0,1\} *$/\1/p" project.yml | sort -u
}

expected_short="$(collect_yaml CFBundleShortVersionString)"
expected_build="$(collect_yaml CFBundleVersion)"

if [[ -z "${expected_short}" || -z "${expected_build}" ]]; then
  echo "error: could not read a version out of project.yml" >&2
  exit 1
fi
if [[ "$(wc -l <<<"${expected_short}")" -ne 1 ]]; then
  fail "project.yml targets declare conflicting CFBundleShortVersionString: $(tr '\n' ' ' <<<"${expected_short}")"
fi
if [[ "$(wc -l <<<"${expected_build}")" -ne 1 ]]; then
  fail "project.yml targets declare conflicting CFBundleVersion: $(tr '\n' ' ' <<<"${expected_build}")"
fi
[[ ${status} -eq 0 ]] || exit 1

for plist in "${SOURCE_PLISTS[@]}"; do
  short="$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "${plist}")"
  build="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "${plist}")"
  [[ "${short}" == "${expected_short}" ]] ||
    fail "${plist} CFBundleShortVersionString is ${short}, project.yml says ${expected_short}"
  [[ "${build}" == "${expected_build}" ]] ||
    fail "${plist} CFBundleVersion is ${build}, project.yml says ${expected_build}"
done

for ruby in "${RUBY_FILES[@]}"; do
  found="$(sed -n 's/^ *version "\([^"]*\)" *$/\1/p' "${ruby}")"
  [[ "${found}" == "${expected_short}" ]] ||
    fail "${ruby} version is ${found:-unset}, project.yml says ${expected_short}"
done

for plist in "${GENERATED_PLISTS[@]}"; do
  if git ls-files --error-unmatch "${plist}" >/dev/null 2>&1; then
    fail "${plist} is generated by xcodegen but tracked by git; add it to .gitignore and run: git rm --cached ${plist}"
  fi
done

if [[ ${status} -ne 0 ]]; then
  echo "" >&2
  echo "Run ./scripts/bump-version.sh <version> <build> instead of editing by hand." >&2
  exit 1
fi

echo "✓ versions agree: ${expected_short} (build ${expected_build})"
