#!/usr/bin/env bash
# Fail if the app family's version numbers have drifted apart.
#
# Two kinds of Info.plist live in this repo and they must not be confused:
#
#   generated  — targets that declare an `info:` block in project.yml. XcodeGen
#                writes these on every `xcodegen generate`, so they are
#                gitignored. Editing them by hand accomplishes nothing.
#   checked in — targets that point at an existing file with `INFOPLIST_FILE`.
#                XcodeGen never touches these, so they are the source of truth
#                for the macOS app and its widget and must be bumped by hand.
#
# A version bump therefore has to touch project.yml *and* the checked-in
# plists. This script is what stops someone from touching only one of them.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

# Checked-in plists: hand-maintained, must match project.yml.
SOURCE_PLISTS=(
  Resources/Info.plist
  Sources/StandUpReminderWidget/Info.plist
)

# Generated plists: must stay untracked or `xcodegen generate` dirties the tree.
GENERATED_PLISTS=(
  Resources/iOS-Info.plist
  Resources/Watch-Info.plist
  Resources/iOSWidget-Info.plist
  Resources/WatchWidget-Info.plist
)

status=0
fail() { echo "error: $*" >&2; status=1; }

# Collect the version each project.yml target declares. All four must agree;
# `sort -u` reduces them to one value, so anything left over is a disagreement.
collect_yaml() {
  sed -n "s/^ *$1: *\"\{0,1\}\([^\"]*\)\"\{0,1\} *$/\1/p" project.yml | sort -u
}

expected_short="$(collect_yaml CFBundleShortVersionString)"
expected_build="$(collect_yaml CFBundleVersion)"

if [[ -z "${expected_short}" || -z "${expected_build}" ]]; then
  echo "error: could not read a version out of project.yml" >&2
  exit 1
fi
if [[ "$(wc -l <<<"${expected_short}")" -ne 1 ]]; then
  fail "project.yml targets declare conflicting CFBundleShortVersionString: $(tr '\n' ' ' <<<"${expected_short}")"
fi
if [[ "$(wc -l <<<"${expected_build}")" -ne 1 ]]; then
  fail "project.yml targets declare conflicting CFBundleVersion: $(tr '\n' ' ' <<<"${expected_build}")"
fi
[[ ${status} -eq 0 ]] || exit 1

for plist in "${SOURCE_PLISTS[@]}"; do
  short="$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "${plist}")"
  build="$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "${plist}")"
  [[ "${short}" == "${expected_short}" ]] ||
    fail "${plist} CFBundleShortVersionString is ${short}, project.yml says ${expected_short}"
  [[ "${build}" == "${expected_build}" ]] ||
    fail "${plist} CFBundleVersion is ${build}, project.yml says ${expected_build}"
done

for plist in "${GENERATED_PLISTS[@]}"; do
  if git ls-files --error-unmatch "${plist}" >/dev/null 2>&1; then
    fail "${plist} is generated by xcodegen but tracked by git; add it to .gitignore and run: git rm --cached ${plist}"
  fi
done

if [[ ${status} -ne 0 ]]; then
  echo "" >&2
  echo "Version bump checklist: project.yml (all four targets), $(printf '%s, ' "${SOURCE_PLISTS[@]}" | sed 's/, $//')." >&2
  exit 1
fi

echo "✓ versions agree: ${expected_short} (build ${expected_build})"
