#!/usr/bin/env bash
# Regenerate docs/LIVE_CLAIMS.md from docs/claims/*.md.
#
# The index exists so an agent reads one table instead of every claim file at
# session start. It is generated; hand edits are overwritten without warning.
set -euo pipefail


ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLAIMS="$ROOT/docs/claims"
OUT="$ROOT/docs/LIVE_CLAIMS.md"

field() {
  # field <file> <name> — read a metadata bullet, before the first "## " heading.
  sed -n '1,/^## /p' "$1" | sed -n "s/^- $2:[[:space:]]*//p" | head -1
}

rows=""
for f in "$CLAIMS"/*.md; do
  [ -e "$f" ] || continue
  case "$(basename "$f")" in README.md) continue ;; esac
  status="$(field "$f" 'Status')"
  case "$status" in
    Active | 'PR Open' | Paused) ;;
    *) continue ;;
  esac
  rows+="| $status | \`$(field "$f" 'Task ID')\` | $(field "$f" 'Tool') | \`$(field "$f" 'Branch')\` | $(field "$f" 'Pull Request') | \`$(basename "$f")\` |"$'\n'
done

[ -n "$rows" ] || rows="| _none_ | | | | | |"$'\n'

# Backticks below are markdown, not command substitution.
# shellcheck disable=SC2016
{
  echo '# Live claims index'
  echo
  echo '_Auto-generated by `scripts/generate-live-claims-index.sh`. Do not hand-edit._'
  echo
  echo "Generated: \`$(date -u +%Y-%m-%dT%H:%MZ)\`"
  echo
  echo 'Statuses included: `Active`, `PR Open`, `Paused`.'
  echo
  echo '| Status | Task ID | Tool | Branch | PR | File |'
  echo '|---|---|---|---|---|---|'
  printf '%s' "$rows"
  echo
  echo '## How to use'
  echo
  echo '1. Scan this table for your tool and any overlapping write surfaces.'
  echo '2. Open only the claim files you need for collision detail.'
  echo '3. Read `docs/ASSIGNMENT.md` next — an empty slot means do not self-select.'
  echo '4. Full protocol: `docs/WORKBOARD.md`.'
} > "$OUT"

echo "Wrote $OUT"
